### PR TITLE
[ACM-7321] Configure alerts to detect acm hub compactor problems

### PR DESCRIPTION
**Pull request by subbarao-meduri**
These alerts are modeled after [RHOBS compactor alerts ](https://github.com/rhobs/configuration/blob/2e740eca3d9321dc916c9d54a17526829d8dffee/resources/observability/prometheusrules/observatorium-thanos-production.prometheusrules.yaml#L79-L151)

### CODE REVIEW

**Comment by bjoydeep** [comment]
@subbarao-meduri we also have seen Thanos fail when the Compactor PV run out of space. It is interesting that you chose not to monitor the space. Probably because it would get reflected in the `halted` metric?

**Comment by subbarao-meduri** [comment]
> @subbarao-meduri we also have seen Compactor fail when the Compactor PV run out of space. It is interesting that you chose not to monitor the space. Probably because it would get reflected in the `halted` metric?

@bjoydeep yes, any underlying infrastructure problems will surface through failing metrics, compactor halting, compactions failing, bucket operations failing etc. We could add another alert for PV size, but I think that would be somewhat redundant, imo.

**Pull request merged**
