### PR TITLE
add Cluster monitoring label 

### PR DESCRIPTION
**Pull request by coleenquadros**
- set {{openshift.io/cluster-monitoring=true }}label on `open-cluster-management-observability` namespaces
- Moved the predicate functions to a new file
- Added test cases for Predicate functions

https://issues.redhat.com/browse/ACM-7631

### CODE REVIEW

**Comment by coleenquadros** [comment]
Screenshot 2023-10-13 at 16 15 24

**Review by saswatamcode — APPROVED** [review]
Thanks! Generally lgtm, just a few small nits.

**Comment by coleenquadros** [comment]
@subbarao-meduri I refactored the predicate functions to another file and added test cases. It still needs more coverage. Let me know if this is good to merge

**Pull request merged**
