### PR TITLE
[ACM-10987]Check SA imagePullSecret length to discard comparing against generate…

### PR DESCRIPTION
**Pull request by philipgough**
…d and injected values

### CODE REVIEW

**Review by saswatamcode — APPROVED** [review]
/lgtm

**Comment by coleenquadros** [comment]
Can you also add a watch logic for the endpoint-sa [ here](https://github.com/stolostron/multicluster-observability-operator/blob/1cb5bad8ffedfe038cc5dbebee399f915241ccf3/operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go#L1033) for the case when its deleted.

**Comment by philipgough** [comment]
Discussed about follow up improvements offline with @coleenquadros which we will push to a new PR

**Pull request merged**
