### PR TITLE
ACM-11987: Add self-managed to ClusterManagementAddOn

### PR DESCRIPTION
**Pull request by jacobbaungard**
Since we're currently not correctly set "supportedConfigs" and "desiredConfig->specHash" on our ManagedClusterAdddon objects, these will never get past "Progressing" in 2.11. This is because the "addon-management-controller" is now specifically looking for these fields to be set.

As a workaround we set `addon.open-cluster-management.io/lifecycle: self` to ensure this does not happen. This should mirror the current behaviour of 2.10.

### CODE REVIEW

**Comment by jacobbaungard** [comment]
Potentially new flaky test? Not sure why this functionality would cause that though.. Order of the labels are occasionally the other way around.

```
 === RUN   TestUpdateAllManagedClusterLabelNames/Add_new_labels
I0619 16:27:17.877657   23955 util.go:125] added managedcluster label: label1
I0619 16:27:17.877668   23955 util.go:125] added managedcluster label: label2
I0619 16:27:17.877730   23955 util.go:189] managed ignore list is empty
    util_test.go:751: syncLabelList.RegexLabelList = [label2 label1], want [label1 label2] 
```

**Review by douglascamata — APPROVED** [review]
/lgtm

**Pull request merged**
