### PR TITLE
Add ACM - OpenShift Virtualization Overview dashboard

### PR DESCRIPTION
**Pull request by sradco**
This PR add the "ACM - OpenShift Virtualization Overview" dashboard that shows details related to the OpenShift Virtualization operator and Virtual machines.

Signed-off-by: Shirly Radco <sradco@redhat.com>

### CODE REVIEW

**Comment by moadz** [comment]
Hey @sradco do you have access to an instance with this dashboard loaded/metrics collected?

**Comment by sradco** [comment]
> Hey @sradco do you have access to an instance with this dashboard loaded/metrics collected?

@moadz I created the PR based on https://github.com/sradco/acm-multi-cluster-kubevirt-dashboard, which includes a screenshot of the dashboard. Do you require an instance with it running?

**Review by moadz — APPROVED** [review]
Reviewed dashboard on instance provided by @sradco, LGTM :)

**Pull request merged**
