### PR TITLE
Updated COMPONENT_VERSION file for release-2.8

### PR DESCRIPTION
**Pull request by dislbenn**
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
/override ci/prow/test-e2e

I am overriding this job to unblock the 2.8 images from being built. The issue that is occurring is around the storage class that is being used for the `minio` PVC. The storage class is using `gp2`; however, the cluster is using `gp3`. We will need to either update the storage class for the cluster or for the `minio` object; however, the latter seems like the better route.

```bash

Name:          minio
Namespace:     open-cluster-management-observability
StorageClass:  gp2
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/name=minio
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       minio-66bd9b6bc6-mgj7l
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  8s (x25 over 6m4s)  persistentvolume-controller  storageclass.storage.k8s.io "gp2" not found
```

**Pull request merged**
