### PR TITLE
Update ocm core setup on kind tests

### PR DESCRIPTION
**Pull request by periklis**
The E2E tests running on kind are currently installing the OCM core (i.e. cluster-manager, klusterlet) using the very old `release-2.4` branch from the [stolostron/registration-operator repository](/stolostron/registration-operator). This branch lacks currently newer components and in particular the `addon-manager` and in turn we cannot test successfully the following PR that incorporates MCOA in MCO:
- #1470 

cc @philipgough

### CODE REVIEW

**Review by philipgough — APPROVED** [review]
/lgtm

**Review by saswatamcode — APPROVED** [review]

**Pull request merged**
