### PR TITLE
Migrate operator-sdk, deps and Makefile targets from v1.4.2 to v.1.34.2

### PR DESCRIPTION
**Pull request by periklis**
The following PR applies a series of migrations to update the MultiClusterObservability operator's operator-sdk tooling and accompanying dependencies from `v1.4.2` to `v1.34.2`. The following migrations were applied:
1. Upgrade the `operator-sdk` from `v1.4.2` to `v1.34.2`
2. Upgrade the `controller-gen` from `v0.4.1` to `v0.11.4`.
   1. Steps: `v0.4.1 -> v0.7.0 -> v0.8.0 -> v0.9.0 -> v0.9.2 -> v0.10.0 -> v0.11.0 -> v0.11.4`
   2. **Note:** Newer version than 0.11 require go 1.22 thus skipped for now!
4. Migrated the `PROJECT` configuration from layout version `go/v3-alpha` to `go/v3`. 
    1. **Note:** Not applied newer project layout based on go/v4 because it requires [significant code base refactorings](https://book.kubebuilder.io/migration/migration_guide_gov3_to_gov4)
5. Updated `operators/multiclusterobservability/Makefile`:
   1. Added missing targets for managing the bundle, i.e. `bundle-build`, `bundle-push`, `catalog-build`, `catalog-push`
   3. Centralized the shell flags for bash as per requirement for kubebuilder/operator-sdk's scripts.
   4. Added support `USE_IMAGE_DIGESTS=true` to generate a bundle using SHA256 digests.
   5. Added support for `make docker-buildx` to enable testing multi-arch image builds locally. 
      **Supported platforms:** `linux/arm64`, `linux/amd64`, l`inux/s390x`, `linux/ppc64le`
   6. Added all missing `.PHONY` directives for phony targets.
7. Remove `admissionReviewVersions={v1beta}` from webhooks as per dropped support since k8s 1.22.

### Notes for the reviewer

* The commits in this PR are outlined as per one for each `operator-sdk` version migration steps. 
* Although each commit represents the migration steps per `operator-sdk` version, some versions are skipped because they did not require any.
* All `operator-sdk` migrations applied are documented here: https://sdk.operatorframework.io/docs/upgrading-sdk-version/

### Open issues:

- [ ] Still unclear if we need this [patch](https://github.com/stolostron/multicluster-observability-operator/blob/3570bc8bdd12f578ecd12db6e072804663f0d9f2/operators/multiclusterobservability/config/manifests/kustomization.yaml) although we have webhooks in place.

### CODE REVIEW

**Comment by moadz** [comment]
@periklis you're a rockstar! Thanks for this. Will wait to merge later :)

**Review by thibaultmg — APPROVED** [review]
/lgtm

**Pull request merged**
