### PR TITLE
add doc for import ocp311 dashboards.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/stolostron/backlog/issues/19120 and https://github.com/stolostron/backlog/issues/13360
Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
@clyang82 PTAL

**Comment by morvencao** [comment]
ref: https://github.com/stolostron/backlog/issues/19065

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
