### PR TITLE
add bvt tag for e2e test cases

### PR DESCRIPTION
**Pull request by marcolan018**
Signed-off-by: Marco llan@redhat.com

@quchangl-github @clyang82 please review the test cases I tagged with BVT, thanks

### CODE REVIEW

**Comment by songleo** [comment]
@quchangl-github FYI

**Comment by songleo** [comment]
I will setup the clusterpool size to run our prow e2e.

**Comment by quchangl-github** [comment]
@marcolan018 May I know why only 3 files test cases are update for BVT tag, how about other test cases?

**Comment by marcolan018** [comment]
@quchangl-github 
the test cases I tagged with BVT only include the ones that make sure observability configuration/function works well after installation, and I think those are the basic requirements.
For others such as test cases for custom configurations, reconcile after manual update, I don't include them

**Pull request merged**
