### PR TITLE
Get Oauth proxy image from ImageStreams resource

### PR DESCRIPTION
**Pull request by coleenquadros**
https://issues.redhat.com/browse/ACM-12538

 Global Hub Ref PR -  https://github.com/stolostron/multicluster-global-hub/pull/1010
  https://github.com/stolostron/multicluster-global-hub/pull/1042

### CODE REVIEW

**Comment by coleenquadros** [comment]
local testing -> 

`│   grafana-proxy:                                                                                                                                                                                                                                                           │
│     Container ID:  cri-o://cc09a0aa12d9e25fca0500669a311279ce3536d7e74dadfbd1329acdc2518574                                                                                                                                                                                │
│     Image:         quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:65515661a7d719f1a8984c8fe3869a8c479c735b601d820c077797fe78b8e6b3                                                                                                                                  │
│     Image ID:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:652cc1022714aa53983339251d81d0610fba78c8b557dd4eedf831126ce3b51d    `

**Review by philipgough — APPROVED** [review]
/lgtm

**Pull request merged**
