### PR TITLE
update to deployer functions for AddOnDeploymentConfig and ClusterManagementAddOn

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
In https://github.com/stolostron/multicluster-observability-operator/pull/1470 we added support for deploying and configuring MCOA with the capabilities field. However, if we enabled a field in capabilities and then disabled it MCO would not reconcile the AddOnDeploymentConfig correctly due to DeepDerivative, which would return true instead of false.

### CODE REVIEW

**Review by philipgough — APPROVED** [review]
/lgtm

**Review by periklis — COMMENTED** [review]
/lgtm

**Review by periklis — APPROVED** [review]
/lgtm

**Pull request merged**
