### PR TITLE
Added github action for updating go modules

### PR DESCRIPTION
**Pull request by dislbenn**
This action will add a workflow to update the go modules version within the repo.

Related Issue: https://github.com/stolostron/backlog/issues/18940
Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

### CODE REVIEW

**Review by subbarao-meduri — APPROVED** [review]
lgtm

**Comment by dislbenn** [comment]
Merging this PR. The changes that were made do not affect the `ci/prow/test-e2e` job.

**Pull request merged**
