### PR TITLE
Add OADP Dashboard

### PR DESCRIPTION
**Pull request by leoaaraujo**
Added grafana dashboard for OADP as discussed with Scott Berens and Joydeep

### CODE REVIEW

**Comment by bjoydeep** [comment]
Hi @leoaaraujo firstly, thank you for adding this! Couple of minor things -

1. as you can see you need to add the signoff during `commit git commit -s ...`
2. we do not use grafana operator. What we do is use a configmap (like OCP used to) to load the grafana dashboards. Its the grafana dashboard yaml, wrapped up in a configmap. An example is here - https://github.com/stolostron/multicluster-observability-operator/blob/main/examples/dashboards/alert-dashboards/alert-analysis.yaml
3. In your readme could you also specify the list of metrics that will be needed to populate this dashboard like `velero_backup_attempt_total`. We will need to add a note to README about that. [Just because Prometheus has those metrics does not mean ACM Observability will have them. We need to inform ACM Observability to gather those from Prometheus using a configmap - `open-cluster-management-observability/observability-metrics-custom-allowlist`

**Comment by leoaaraujo** [comment]
Hi @Joydeep Banerjee ***@***.***> ,

Thanks for your comments.

I will work on this changes. about the signoff, I did make only in the last
commit, I will adjust and to create a new PR.



Leonardo Araujo

Senior Consultant, RHCA

RED HAT SPAIN <https://www.redhat.com/>
Torre de Cristal
Paseo de la Castellana 259C
28046 Madrid Spain

***@***.***
M: +34-669-486-256
@RedHat <https://twitter.com/redhat>   Red Hat
<https://www.linkedin.com/company/red-hat>  Red Hat
<https://www.facebook.com/RedHatInc>
<https://www.redhat.com/>

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
Will close this PR and merge the newer one.

**Pull request closed without merging**
