### PR TITLE
[ACM-5058] Use cluster_version metric for cluster label_values (#1177)

### PR DESCRIPTION
**Pull request by dislbenn**
Switch to using cluster_version metric instead of the expensive kube_pod_info metric to obtain cluster labels

### CODE REVIEW

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
Closing this PR. The changes in this PR was identified to break filtering *ks clusters in Grafana. Will close this PR and add the `storageClassName` changes to this PR: https://github.com/stolostron/multicluster-observability-operator/pull/1222

**Pull request closed without merging**
