### PR TITLE
RHOBS-957: Allow Thanos args overwrite.

### PR DESCRIPTION
**Pull request by jacobbaungard**
With this PR we now allow overwriting of Thanos CLI arguments.

Example that shows how to for overwriting receive CLI args. Note ALL args are overwritten and must be present in the  spec.

```
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
  advanced:
    receive:
      containers:
        - name: thanos-receive
          args:
          - receive
          - --log.level=debug
          - --log.format=logfmt
          - --grpc-address=0.0.0.0:10901
          - --http-address=0.0.0.0:10902
          - --remote-write.address=0.0.0.0:19291
          - --receive.replication-factor=1
          - --tsdb.path=/var/thanos/receive
          - --tsdb.retention=4d
          - --label=replica="$(NAME)"
          - --label=receive="true"
          - --objstore.config=$(OBJSTORE_CONFIG)
          - --receive.local-endpoint=$(NAME).observatorium-xyz-thanos-receive-default.$(NAMESPACE).svc.cluster.local:10901
          - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
          - --receive.default-tenant-id="default-tenant-test123456"
```

### CODE REVIEW

**Review by thibaultmg — APPROVED** [review]
/lgtm

**Review by coleenquadros — APPROVED** [review]

**Pull request merged**
